services:
  event-service:
    extends:
      file: ./event-service/docker-compose.yaml
      service: event-service
    environment:
      - HTTP_PROXY=hoverfly:8500
    depends_on:
      - hoverfly
  